### ISSUE TITLE
Skin tones support

### ISSUE THREAD

**Issue by Maestroschan** [Maestroschan/emoji-selector-for-gnome#30]
Since color emojis are supported on most systems:

- [x] add unicode 10 (and 11) "person" emojis i didn't add because of poor support (#28)
- [x] there is a ton of them, they might need their own category (#31)
- [x] implement the #31 tag system
- [x] the submenu with category's title should be used for skin tone selection 
![](https://i.imgur.com/h0cLnGv.png)

- [x] while skin tone shall be a setting key, gender will just be ignored for the moment (all emojis twice)
- [x] tone will be added by concatenation
